// GENERATED by tools/gen_c31_decode.py -- do not edit.
// The handler set the RTL implements. Everything else in MAME's
// 2,048-entry table decodes to OP_UNIMPL and raises `unimplemented`,
// so the lockstep depth is a measurement of exactly this list.
//
// The values are SIZED (`8'dN`): Quartus 17.0.2 requires an
// enumeration's member values to match its base type's width, and an
// unsized literal is 32 bits wide.
`ifndef C31_OPS_SVH
`define C31_OPS_SVH
typedef enum logic [7:0] {
	OP_UNIMPL         = 8'd0  ,
	OP_BR_IMM         = 8'd1  ,
	OP_LDI_IMM        = 8'd2  ,
	OP_LDIU_IMM       = 8'd3  ,
	OP_LDI_DIR        = 8'd4  ,
	OP_LDI_REG        = 8'd5  ,
	OP_CMPI_IMM       = 8'd6  ,
	OP_BRC_IMM        = 8'd7  ,
	OP_LDI_IND        = 8'd8  ,
	OP_BRCD_IMM       = 8'd9  ,
	OP_SUBI_IMM       = 8'd10 ,
	OP_RPTB_IMM       = 8'd11 ,
	OP_LDISTI         = 8'd12 ,
	OP_CALL_IMM       = 8'd13 ,
	OP_STI_IND        = 8'd14 ,
	OP_STI_DIR        = 8'd15 ,
	OP_AND_IMM        = 8'd16 ,
	OP_ANDN_IMM       = 8'd17 ,
	OP_OR_IMM         = 8'd18 ,
	OP_NOP_REG        = 8'd19 ,
	OP_LDIEQ_IMM      = 8'd20 ,
	OP_LDINE_IMM      = 8'd21 ,
	OP_RETSC_REG      = 8'd22 ,
	OP_CMPI_REG       = 8'd23 ,
	OP_LSH_IMM        = 8'd24 ,
	OP_PUSH           = 8'd25 ,
	OP_ADDI_IMM       = 8'd26 ,
	OP_MPYI_IMM       = 8'd27 ,
	OP_ADDI3_REGREG   = 8'd28 ,
	OP_BRCD_REG       = 8'd29 ,
	OP_BRC_REG        = 8'd30 ,
	OP_MPYI3_REGREG   = 8'd31 ,
	OP_ADDI_DIR       = 8'd32 ,
	OP_STISTI         = 8'd33 ,
	OP_LDIHI_IMM      = 8'd34 ,
	OP_LDILS_DIR      = 8'd35 ,
	OP_CMPI_DIR       = 8'd36 ,
	OP_LSH3_REGREG    = 8'd37 ,
	OP_ADDI_REG       = 8'd38 ,
	OP_POP            = 8'd39 ,
	OP_OR_REG         = 8'd40 ,
	OP_LDF_IMM        = 8'd41 ,
	OP_STF_IND        = 8'd42 ,
	OP_LDF_DIR        = 8'd43 ,
	OP_ANDN_REG       = 8'd44 ,
	OP_PUSHF          = 8'd45 ,
	OP_CMPI3_INDIND   = 8'd46 ,
	OP_MPYI3_INDREG   = 8'd47 ,
	OP_STF_DIR        = 8'd48 ,
	OP_OR3_INDREG     = 8'd49 ,
	OP_XOR_IMM        = 8'd50 ,
	OP_ADDI_IND       = 8'd51 ,
	OP_POPF           = 8'd52 ,
	OP_RETIC_REG      = 8'd53 ,
	OP_LDF_IND        = 8'd54 ,
	OP_CMPI_IND       = 8'd55 ,
	OP_MPYF3_REGREG   = 8'd56 ,
	OP_MPYF_IND       = 8'd57 ,
	OP_MPYF_REG       = 8'd58 ,
	OP_LDF_REG        = 8'd59 ,
	OP_MPYF3_INDREG   = 8'd60 ,
	OP_MPYADDF_3      = 8'd61 ,
	OP_ADDF3_REGIND   = 8'd62 ,
	OP_FIX_IND        = 8'd63 ,
	OP_ASH_IMM        = 8'd64 ,
	OP_CALLC_REG      = 8'd65 ,
	OP_CMPF_DIR       = 8'd66 ,
	OP_SUBF_IND       = 8'd67 ,
	OP_ADDF_IND       = 8'd68 ,
	OP_FIX_REG        = 8'd69 ,
	OP_FLOAT_REG      = 8'd70 ,
	OP_SUBF3_REGREG   = 8'd71 ,
	OP_AND3_REGREG    = 8'd72 ,
	OP_ADDF_REG       = 8'd73 ,
	OP_MPYF_DIR       = 8'd74 ,
	OP_NEGF_IND       = 8'd75 ,
	OP_CMPI3_INDREG   = 8'd76 ,
	OP_ADDI3_INDREG   = 8'd77 ,
	OP_SUBF_REG       = 8'd78 ,
	OP_CMPF_IND       = 8'd79 ,
	OP_LDIHI_REG      = 8'd80 ,
	OP_LSH3_INDREG    = 8'd81 ,
	OP_ASH3_INDREG    = 8'd82 ,
	OP_LDINE_IND      = 8'd83 ,
	OP_LDINE_REG      = 8'd84 ,
	OP_LDFGE_IMM      = 8'd85 ,
	OP_FLOAT_IND      = 8'd86 ,
	OP_LDFLT_DIR      = 8'd87 ,
	OP_CMPF_IMM       = 8'd88 ,
	OP_CMPF_REG       = 8'd89 ,
	OP_TSTB_IMM       = 8'd90 ,
	OP_XOR3_REGREG    = 8'd91 ,
	OP_ABSI_REG       = 8'd92 ,
	OP_LDILT_REG      = 8'd93 ,
	OP_SUBI_IND       = 8'd94 ,
	OP_NEGI_REG       = 8'd95 ,
	OP_LDILT_IND      = 8'd96 ,
	OP_LDIGE_IMM      = 8'd97 ,
	OP_TSTB_DIR       = 8'd98 ,
	OP_SUBRI_IMM      = 8'd99 ,
	OP_LDFGT_IMM      = 8'd100,
	OP_ASH3_REGREG    = 8'd101,
	OP_SUBF3_INDREG   = 8'd102,
	OP_LDFSTF         = 8'd103,
	OP_MPYF_IMM       = 8'd104,
	OP_MPYI_IND       = 8'd105,
	OP_AND_DIR        = 8'd106,
	OP_SUBRI_IND      = 8'd107,
	OP_LDINE_DIR      = 8'd108,
	OP_LDIEQ_DIR      = 8'd109,
	OP_ADDF_IMM       = 8'd110,
	OP_ASH_REG        = 8'd111,
	OP_SUBI3_REGREG   = 8'd112,
	OP_LSH_REG        = 8'd113,
	OP_SUBI_REG       = 8'd114,
	OP_AND_REG        = 8'd115,
	OP_XOR_REG        = 8'd116,
	OP_SUBC_REG       = 8'd117,
	OP_AND_IND        = 8'd118,
	OP_NEGI_IND       = 8'd119,
	OP_SUBI3_INDREG   = 8'd120,
	OP_AND3_INDREG    = 8'd121,
	OP_ANDN3_INDREG   = 8'd122,
	OP_ADDI3_REGIND   = 8'd123,
	OP_LDIHS_REG      = 8'd124,
	OP_LDIHS_IMM      = 8'd125,
	OP_LDILO_IMM      = 8'd126,
	OP_LDFLT_REG      = 8'd127,
	OP_LDFGT_REG      = 8'd128,
	OP_LDFLT_IMM      = 8'd129,
	OP_LDFGE_DIR      = 8'd130,
	OP_LDFLT_IND      = 8'd131,
	OP_LDFGT_IND      = 8'd132,
	OP_NEGF_REG       = 8'd133,
	OP_ABSF_REG       = 8'd134,
	OP_RND_REG        = 8'd135,
	OP_LDE_REG        = 8'd136,
	OP_SUBF_IMM       = 8'd137,
	OP_SUBRF_IMM      = 8'd138,
	OP_ADDF_DIR       = 8'd139,
	OP_SUBF_DIR       = 8'd140,
	OP_ADDF3_REGREG   = 8'd141,
	OP_MPYF3_REGIND   = 8'd142,
	OP_MPYF3STF       = 8'd143,
	OP_RPTS_REG       = 8'd144
} c31_op_e;

// The condition code baked into a conditional load's NAME, from
// MAME's own COND_BITS. `OP_x: cond = N`. Derived from the
// name with the model's own rule, for every conditional load.
`define C31_NAMED_COND(k, out) \
	if (k == OP_LDFGE_DIR     ) out = 5'd10; else \
	if (k == OP_LDFGE_IMM     ) out = 5'd10; else \
	if (k == OP_LDFGT_IMM     ) out = 5'd9 ; else \
	if (k == OP_LDFGT_IND     ) out = 5'd9 ; else \
	if (k == OP_LDFGT_REG     ) out = 5'd9 ; else \
	if (k == OP_LDFLT_DIR     ) out = 5'd7 ; else \
	if (k == OP_LDFLT_IMM     ) out = 5'd7 ; else \
	if (k == OP_LDFLT_IND     ) out = 5'd7 ; else \
	if (k == OP_LDFLT_REG     ) out = 5'd7 ; else \
	if (k == OP_LDIEQ_DIR     ) out = 5'd5 ; else \
	if (k == OP_LDIEQ_IMM     ) out = 5'd5 ; else \
	if (k == OP_LDIGE_IMM     ) out = 5'd10; else \
	if (k == OP_LDIHI_IMM     ) out = 5'd3 ; else \
	if (k == OP_LDIHI_REG     ) out = 5'd3 ; else \
	if (k == OP_LDIHS_IMM     ) out = 5'd4 ; else \
	if (k == OP_LDIHS_REG     ) out = 5'd4 ; else \
	if (k == OP_LDILO_IMM     ) out = 5'd1 ; else \
	if (k == OP_LDILS_DIR     ) out = 5'd2 ; else \
	if (k == OP_LDILT_IND     ) out = 5'd7 ; else \
	if (k == OP_LDILT_REG     ) out = 5'd7 ; else \
	if (k == OP_LDINE_DIR     ) out = 5'd6 ; else \
	if (k == OP_LDINE_IMM     ) out = 5'd6 ; else \
	if (k == OP_LDINE_IND     ) out = 5'd6 ; else \
	if (k == OP_LDINE_REG     ) out = 5'd6 ; else \
	if (k == OP_LDIU_IMM      ) out = 5'd0 ; else \
	out = 5'd0;

// ...and whether the handler IS one: its condition comes from the
// name, not from the instruction's bits 20:16 (which are its
// destination register).
`define C31_IS_NAMED_COND(k) ( \
	(k == OP_LDFGE_DIR) || \
	(k == OP_LDFGE_IMM) || \
	(k == OP_LDFGT_IMM) || \
	(k == OP_LDFGT_IND) || \
	(k == OP_LDFGT_REG) || \
	(k == OP_LDFLT_DIR) || \
	(k == OP_LDFLT_IMM) || \
	(k == OP_LDFLT_IND) || \
	(k == OP_LDFLT_REG) || \
	(k == OP_LDIEQ_DIR) || \
	(k == OP_LDIEQ_IMM) || \
	(k == OP_LDIGE_IMM) || \
	(k == OP_LDIHI_IMM) || \
	(k == OP_LDIHI_REG) || \
	(k == OP_LDIHS_IMM) || \
	(k == OP_LDIHS_REG) || \
	(k == OP_LDILO_IMM) || \
	(k == OP_LDILS_DIR) || \
	(k == OP_LDILT_IND) || \
	(k == OP_LDILT_REG) || \
	(k == OP_LDINE_DIR) || \
	(k == OP_LDINE_IMM) || \
	(k == OP_LDINE_IND) || \
	(k == OP_LDINE_REG) || \
	(k == OP_LDIU_IMM) || \
	1'b0 )
`endif
