// GENERATED by tools/gen_c31_decode.py -- do not edit.
// The decode over op[31:21], which is MAME's own dispatch index.
// Only the implemented handlers appear; everything else is
// OP_UNIMPL. 232 of 2048 indices, in 144 contiguous run(s).
//
// An if/else chain rather than a case: Verilog case labels cannot
// carry RANGES (that is `case inside`, which iverilog does not
// take), and a run of 16 indices spelled out sixteen times would
// be the table transcribed rather than generated.
`ifndef C31_DECODE_SVH
`define C31_DECODE_SVH
`define C31_DECODE(idx, out) \
	if (idx == 11'h000)                           out = OP_ABSF_REG    ; else \
	if (idx == 11'h004)                           out = OP_ABSI_REG    ; else \
	if (idx == 11'h00C)                           out = OP_ADDF_REG    ; else \
	if (idx == 11'h00D)                           out = OP_ADDF_DIR    ; else \
	if (idx == 11'h00E)                           out = OP_ADDF_IND    ; else \
	if (idx == 11'h00F)                           out = OP_ADDF_IMM    ; else \
	if (idx == 11'h010)                           out = OP_ADDI_REG    ; else \
	if (idx == 11'h011)                           out = OP_ADDI_DIR    ; else \
	if (idx == 11'h012)                           out = OP_ADDI_IND    ; else \
	if (idx == 11'h013)                           out = OP_ADDI_IMM    ; else \
	if (idx == 11'h014)                           out = OP_AND_REG     ; else \
	if (idx == 11'h015)                           out = OP_AND_DIR     ; else \
	if (idx == 11'h016)                           out = OP_AND_IND     ; else \
	if (idx == 11'h017)                           out = OP_AND_IMM     ; else \
	if (idx == 11'h018)                           out = OP_ANDN_REG    ; else \
	if (idx == 11'h01B)                           out = OP_ANDN_IMM    ; else \
	if (idx == 11'h01C)                           out = OP_ASH_REG     ; else \
	if (idx == 11'h01F)                           out = OP_ASH_IMM     ; else \
	if (idx == 11'h020)                           out = OP_CMPF_REG    ; else \
	if (idx == 11'h021)                           out = OP_CMPF_DIR    ; else \
	if (idx == 11'h022)                           out = OP_CMPF_IND    ; else \
	if (idx == 11'h023)                           out = OP_CMPF_IMM    ; else \
	if (idx == 11'h024)                           out = OP_CMPI_REG    ; else \
	if (idx == 11'h025)                           out = OP_CMPI_DIR    ; else \
	if (idx == 11'h026)                           out = OP_CMPI_IND    ; else \
	if (idx == 11'h027)                           out = OP_CMPI_IMM    ; else \
	if (idx == 11'h028)                           out = OP_FIX_REG     ; else \
	if (idx == 11'h02A)                           out = OP_FIX_IND     ; else \
	if (idx == 11'h02C)                           out = OP_FLOAT_REG   ; else \
	if (idx == 11'h02E)                           out = OP_FLOAT_IND   ; else \
	if (idx == 11'h034)                           out = OP_LDE_REG     ; else \
	if (idx == 11'h038)                           out = OP_LDF_REG     ; else \
	if (idx == 11'h039)                           out = OP_LDF_DIR     ; else \
	if (idx == 11'h03A)                           out = OP_LDF_IND     ; else \
	if (idx == 11'h03B)                           out = OP_LDF_IMM     ; else \
	if (idx == 11'h040)                           out = OP_LDI_REG     ; else \
	if (idx == 11'h041)                           out = OP_LDI_DIR     ; else \
	if (idx == 11'h042)                           out = OP_LDI_IND     ; else \
	if (idx == 11'h043)                           out = OP_LDI_IMM     ; else \
	if (idx == 11'h04C)                           out = OP_LSH_REG     ; else \
	if (idx == 11'h04F)                           out = OP_LSH_IMM     ; else \
	if (idx == 11'h050)                           out = OP_MPYF_REG    ; else \
	if (idx == 11'h051)                           out = OP_MPYF_DIR    ; else \
	if (idx == 11'h052)                           out = OP_MPYF_IND    ; else \
	if (idx == 11'h053)                           out = OP_MPYF_IMM    ; else \
	if (idx == 11'h056)                           out = OP_MPYI_IND    ; else \
	if (idx == 11'h057)                           out = OP_MPYI_IMM    ; else \
	if (idx == 11'h05C)                           out = OP_NEGF_REG    ; else \
	if (idx == 11'h05E)                           out = OP_NEGF_IND    ; else \
	if (idx == 11'h060)                           out = OP_NEGI_REG    ; else \
	if (idx == 11'h062)                           out = OP_NEGI_IND    ; else \
	if (idx == 11'h064)                           out = OP_NOP_REG     ; else \
	if (idx == 11'h071)                           out = OP_POP         ; else \
	if (idx == 11'h075)                           out = OP_POPF        ; else \
	if (idx == 11'h079)                           out = OP_PUSH        ; else \
	if (idx == 11'h07D)                           out = OP_PUSHF       ; else \
	if (idx == 11'h080)                           out = OP_OR_REG      ; else \
	if (idx == 11'h083)                           out = OP_OR_IMM      ; else \
	if (idx == 11'h088)                           out = OP_RND_REG     ; else \
	if (idx == 11'h09C)                           out = OP_RPTS_REG    ; else \
	if (idx == 11'h0A1)                           out = OP_STF_DIR     ; else \
	if (idx == 11'h0A2)                           out = OP_STF_IND     ; else \
	if (idx == 11'h0A9)                           out = OP_STI_DIR     ; else \
	if (idx == 11'h0AA)                           out = OP_STI_IND     ; else \
	if (idx == 11'h0B8)                           out = OP_SUBC_REG    ; else \
	if (idx == 11'h0BC)                           out = OP_SUBF_REG    ; else \
	if (idx == 11'h0BD)                           out = OP_SUBF_DIR    ; else \
	if (idx == 11'h0BE)                           out = OP_SUBF_IND    ; else \
	if (idx == 11'h0BF)                           out = OP_SUBF_IMM    ; else \
	if (idx == 11'h0C0)                           out = OP_SUBI_REG    ; else \
	if (idx == 11'h0C2)                           out = OP_SUBI_IND    ; else \
	if (idx == 11'h0C3)                           out = OP_SUBI_IMM    ; else \
	if (idx == 11'h0CB)                           out = OP_SUBRF_IMM   ; else \
	if (idx == 11'h0CE)                           out = OP_SUBRI_IND   ; else \
	if (idx == 11'h0CF)                           out = OP_SUBRI_IMM   ; else \
	if (idx == 11'h0D1)                           out = OP_TSTB_DIR    ; else \
	if (idx == 11'h0D3)                           out = OP_TSTB_IMM    ; else \
	if (idx == 11'h0D4)                           out = OP_XOR_REG     ; else \
	if (idx == 11'h0D7)                           out = OP_XOR_IMM     ; else \
	if (idx == 11'h104)                           out = OP_ADDF3_REGREG; else \
	if (idx == 11'h106)                           out = OP_ADDF3_REGIND; else \
	if (idx == 11'h108)                           out = OP_ADDI3_REGREG; else \
	if (idx == 11'h109)                           out = OP_ADDI3_INDREG; else \
	if (idx == 11'h10A)                           out = OP_ADDI3_REGIND; else \
	if (idx == 11'h10C)                           out = OP_AND3_REGREG ; else \
	if (idx == 11'h10D)                           out = OP_AND3_INDREG ; else \
	if (idx == 11'h111)                           out = OP_ANDN3_INDREG; else \
	if (idx == 11'h114)                           out = OP_ASH3_REGREG ; else \
	if (idx == 11'h115)                           out = OP_ASH3_INDREG ; else \
	if (idx == 11'h11D)                           out = OP_CMPI3_INDREG; else \
	if (idx == 11'h11F)                           out = OP_CMPI3_INDIND; else \
	if (idx == 11'h120)                           out = OP_LSH3_REGREG ; else \
	if (idx == 11'h121)                           out = OP_LSH3_INDREG ; else \
	if (idx == 11'h124)                           out = OP_MPYF3_REGREG; else \
	if (idx == 11'h125)                           out = OP_MPYF3_INDREG; else \
	if (idx == 11'h126)                           out = OP_MPYF3_REGIND; else \
	if (idx == 11'h128)                           out = OP_MPYI3_REGREG; else \
	if (idx == 11'h129)                           out = OP_MPYI3_INDREG; else \
	if (idx == 11'h12D)                           out = OP_OR3_INDREG  ; else \
	if (idx == 11'h134)                           out = OP_SUBF3_REGREG; else \
	if (idx == 11'h135)                           out = OP_SUBF3_INDREG; else \
	if (idx == 11'h138)                           out = OP_SUBI3_REGREG; else \
	if (idx == 11'h139)                           out = OP_SUBI3_INDREG; else \
	if (idx == 11'h140)                           out = OP_XOR3_REGREG ; else \
	if (idx == 11'h21C)                           out = OP_LDFLT_REG   ; else \
	if (idx == 11'h21D)                           out = OP_LDFLT_DIR   ; else \
	if (idx == 11'h21E)                           out = OP_LDFLT_IND   ; else \
	if (idx == 11'h21F)                           out = OP_LDFLT_IMM   ; else \
	if (idx == 11'h224)                           out = OP_LDFGT_REG   ; else \
	if (idx == 11'h226)                           out = OP_LDFGT_IND   ; else \
	if (idx == 11'h227)                           out = OP_LDFGT_IMM   ; else \
	if (idx == 11'h229)                           out = OP_LDFGE_DIR   ; else \
	if (idx == 11'h22B)                           out = OP_LDFGE_IMM   ; else \
	if (idx == 11'h283)                           out = OP_LDIU_IMM    ; else \
	if (idx == 11'h287)                           out = OP_LDILO_IMM   ; else \
	if (idx == 11'h289)                           out = OP_LDILS_DIR   ; else \
	if (idx == 11'h28C)                           out = OP_LDIHI_REG   ; else \
	if (idx == 11'h28F)                           out = OP_LDIHI_IMM   ; else \
	if (idx == 11'h290)                           out = OP_LDIHS_REG   ; else \
	if (idx == 11'h293)                           out = OP_LDIHS_IMM   ; else \
	if (idx == 11'h295)                           out = OP_LDIEQ_DIR   ; else \
	if (idx == 11'h297)                           out = OP_LDIEQ_IMM   ; else \
	if (idx == 11'h298)                           out = OP_LDINE_REG   ; else \
	if (idx == 11'h299)                           out = OP_LDINE_DIR   ; else \
	if (idx == 11'h29A)                           out = OP_LDINE_IND   ; else \
	if (idx == 11'h29B)                           out = OP_LDINE_IMM   ; else \
	if (idx == 11'h29C)                           out = OP_LDILT_REG   ; else \
	if (idx == 11'h29E)                           out = OP_LDILT_IND   ; else \
	if (idx == 11'h2AB)                           out = OP_LDIGE_IMM   ; else \
	if (idx >= 11'h300 && idx <= 11'h307)         out = OP_BR_IMM      ; else \
	if (idx >= 11'h310 && idx <= 11'h317)         out = OP_CALL_IMM    ; else \
	if (idx >= 11'h320 && idx <= 11'h327)         out = OP_RPTB_IMM    ; else \
	if (idx == 11'h340)                           out = OP_BRC_REG     ; else \
	if (idx == 11'h341)                           out = OP_BRCD_REG    ; else \
	if (idx == 11'h350)                           out = OP_BRC_IMM     ; else \
	if (idx == 11'h351)                           out = OP_BRCD_IMM    ; else \
	if (idx == 11'h380)                           out = OP_CALLC_REG   ; else \
	if (idx == 11'h3C0)                           out = OP_RETIC_REG   ; else \
	if (idx == 11'h3C4)                           out = OP_RETSC_REG   ; else \
	if (idx >= 11'h418 && idx <= 11'h41F)         out = OP_MPYADDF_3   ; else \
	if (idx >= 11'h610 && idx <= 11'h61F)         out = OP_STISTI      ; else \
	if (idx >= 11'h6C0 && idx <= 11'h6CF)         out = OP_LDFSTF      ; else \
	if (idx >= 11'h6D0 && idx <= 11'h6DF)         out = OP_LDISTI      ; else \
	if (idx >= 11'h6F0 && idx <= 11'h6FF)         out = OP_MPYF3STF    ; else \
	out = OP_UNIMPL;
`endif
